name: CI

on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: |
          yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        typescript-version:
          ['~4.5.0', latest]
        include:
          - typescript-version: '~4.5.0'
            experimental: false
            name: 'ts-4.5'
          - typescript-version: latest
            experimental: false
            name: 'ts-stable'

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: |
          yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run: |
          yarn add typescript@${{ matrix.typescript-version}}
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
