name: Tests

on:
  push:
    branches:
      - main
 
jobs:  

  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache 
        uses: actions/cache@v2
        with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
         
            # Generate a new cache whenever packages or source files change.
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
            # If source files changed but packages didn't, rebuild from a prior cache.
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
              
      # runs all cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          build: npm run build
          start: npm start
          
      # jest tests same as cy
      - name: Jest run
        run: npm test 
